### ISSUE TITLE
Team_Landing_Page

### ISSUE THREAD

**Issue by jeandre-botha** [cos301-2019-se/Defendr#2]
Create the team landing page on the cs website

**Comment by SisaKhoza** [comment]
I'm going to split the page into two sections; team details and individual member details.

As for the former, it will comprise of stakeholder write-downs, repo link team picture and philosophy.

For the individual member sections, my structure will follow so:
Name(s)
Position
Skills
A motivational bit about yourself/Your philosophy

Anything to add/remove?

**Comment by SisaKhoza** [comment]
Heads up on this not, Moe has completed the page and just needs to have the individual's heading's fileld in 👌
