### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by Christo08** [cos301-2019-se/Defendr#57]
Implementation of Prometheus Monitoring to gather (just as initial data, and will be extended):
System overhead
Disk size
Overall/Passed/Dropped packets

Further implementing Grafana to present the data in graphs

**Comment by SisaKhoza** [comment]
A heads up;
Prometheus needs to languages; Go (GoLang) and PromQL (Prometheus Query Language), so I suggest a a read-over of those is sufficient.  Some surface level resources though for terminology:
Prometheus x Grafana setup: https://www.youtube.com/watch?v=4WWW2ZLEg74
What is Go: https://www.youtube.com/watch?v=s_gRXOsrDAA
Go in 12 minutes: https://www.youtube.com/watch?v=C8LgvuEBraI

**Comment by naude-r** [comment]
hi,

please note that prometheus does not require golang. there are several libraries for a number of languages, e.g. java, etc.
https://prometheus.io/docs/instrumenting/clientlibs/

promql is the prometheus query language. this is used from grafana to create the dashboards.

**Comment by SisaKhoza** [comment]
This page makes more sense, thanks Roelof
