### ISSUE TITLE
SRS_Document_Trace-ability-Matrix

### ISSUE THREAD

**Issue by jeandre-botha** [cos301-2019-se/Defendr#8]
A matrix with requirements numbers as rows and the sub-systems as columns.  Include both functional and quality requirements.Indicate with x in the cells which subsystem will implement the solution to satisfy the requirement

**Comment by SisaKhoza** [comment]
Guys,

The matrix is complete, however there is also a priority column.  I'll be leaving all of the requirements at "1", and then we can look at what order things should be implemented in.
